'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createTranslator } = require('../src/i18n');
const { runContextPack } = require('../src/commands/context-pack');

function createCollectLogger() {
  const lines = [];
  return {
    lines,
    log(line) {
      lines.push(String(line));
    },
    error(line) {
      lines.push(String(line));
    }
  };
}

test('context:pack generates a focused context pack from existing memory and scan maps', async () => {
  const projectDir = await fs.mkdtemp(path.join(os.tmpdir(), 'aioson-context-pack-'));

  try {
    await fs.mkdir(path.join(projectDir, '.aioson', 'context'), { recursive: true });
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'project.context.md'),
      'framework: next\nclassification: SMALL\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'discovery.md'),
      '# Discovery\n\n## 6. Existing patterns and conventions\n- Preserve src/editor structure\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'skeleton-system.md'),
      '# System Skeleton\n\n## File map\nsrc/editor/\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'architecture.md'),
      '# Architecture\n\n## Modules\n- editor service\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'spec.md'),
      [
        '# Spec',
        '',
        '## Stack',
        '- Next.js',
        '',
        '## Estado atual',
        '- Caption editor ativo',
        '',
        '### Em andamento',
        '- Ajustar atalhos de teclado',
        '',
        '### Planejado',
        '- Revisar fluxo do YouTube',
        '',
        '## Decisoes em aberto',
        '- Definir fallback de upload',
        '',
        '## Decisoes tomadas',
        '- Manter editor em src/editor',
        '',
        '## Notas',
        '- Nao quebrar autosave'
      ].join('\n'),
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'scan-src.md'),
      [
        '# Folder Scan: src',
        '_Generated by aioson scan:project — 2026-03-19T12:00:00Z_',
        '',
        '## Scope',
        '- Requested folder: `src/`',
        '',
        '## Tree',
        '```text',
        '|-- src/',
        '|  |-- editor/',
        '|  |  |-- caption-editor.ts',
        '|  |-- youtube/',
        '|  |  |-- upload.ts',
        '```'
      ].join('\n'),
      'utf8'
    );

    const { t } = createTranslator('pt-BR');
    const logger = createCollectLogger();
    const result = await runContextPack({
      args: [projectDir],
      options: {
        agent: 'dev',
        goal: 'ajustar captions do editor do YouTube',
        module: 'src',
        'max-files': 6
      },
      logger,
      t
    });

    assert.equal(result.ok, true);
    assert.equal(result.agent, 'dev');
    assert.equal(result.goal, 'ajustar captions do editor do YouTube');
    assert.equal(result.module, 'src');
    assert.equal(result.maxFiles, 6);
    assert.equal(result.selectedFiles.length > 0, true);

    const memoryIndexPath = path.join(projectDir, '.aioson', 'context', 'memory-index.md');
    const specCurrentPath = path.join(projectDir, '.aioson', 'context', 'spec-current.md');
    const specHistoryPath = path.join(projectDir, '.aioson', 'context', 'spec-history.md');
    const modulePath = path.join(projectDir, '.aioson', 'context', 'module-src.md');
    const packContent = await fs.readFile(result.packPath, 'utf8');
    const memoryIndexContent = await fs.readFile(memoryIndexPath, 'utf8');
    const specCurrentContent = await fs.readFile(specCurrentPath, 'utf8');
    const specHistoryContent = await fs.readFile(specHistoryPath, 'utf8');
    const moduleContent = await fs.readFile(modulePath, 'utf8');

    assert.match(packContent, /# Context Pack/);
    assert.match(packContent, /Agent: @dev/);
    assert.match(packContent, /Goal: ajustar captions do editor do YouTube/);
    assert.match(packContent, /module-src\.md/);
    assert.match(packContent, /spec-current\.md/);
    assert.match(packContent, /discovery\.md/);
    assert.match(memoryIndexContent, /# Memory Index/);
    assert.match(specCurrentContent, /# Spec Current/);
    assert.match(specCurrentContent, /Ajustar atalhos de teclado/);
    assert.match(specHistoryContent, /# Spec History/);
    assert.match(specHistoryContent, /Manter editor em src\/editor/);
    assert.match(moduleContent, /# Module Memory: src/);
    assert.equal(logger.lines.some((line) => line.includes('Context pack escrito em')), true);
    assert.equal(logger.lines.some((line) => line.includes('Arquivos incluidos no pack')), true);
  } finally {
    await fs.rm(projectDir, { recursive: true, force: true });
  }
});

test('context:pack considers goal terms even when agent is provided for bootstrap memory', async () => {
  const projectDir = await fs.mkdtemp(path.join(os.tmpdir(), 'aioson-context-pack-bootstrap-'));

  try {
    await fs.mkdir(path.join(projectDir, '.aioson', 'context', 'bootstrap'), { recursive: true });
    await fs.writeFile(path.join(projectDir, '.aioson', 'context', 'project.context.md'), 'framework: node\n', 'utf8');
    await fs.writeFile(path.join(projectDir, '.aioson', 'context', 'discovery.md'), '# Discovery\n', 'utf8');
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'bootstrap', 'what-is.md'),
      '# What Is\n\nSystem identity.\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'bootstrap', 'how-it-works.md'),
      '# How It Works\n\nSystem mechanics.\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'bootstrap', 'what-it-does.md'),
      '# What It Does\n\nSystem features.\n',
      'utf8'
    );
    await fs.writeFile(
      path.join(projectDir, '.aioson', 'context', 'bootstrap', 'current-state.md'),
      '# Current State\n\nSystem state.\n',
      'utf8'
    );

    const { t } = createTranslator('en');
    const result = await runContextPack({
      args: [projectDir],
      options: {
        agent: 'deyvin',
        goal: 'active memory bootstrap',
        'max-files': 8,
        json: true
      },
      logger: createCollectLogger(),
      t
    });

    const selected = result.selectedFiles.map((file) => file.path);
    assert.ok(selected.includes('.aioson/context/bootstrap/what-is.md'));
    assert.ok(selected.includes('.aioson/context/bootstrap/how-it-works.md'));
    assert.ok(selected.includes('.aioson/context/bootstrap/what-it-does.md'));
    assert.ok(selected.includes('.aioson/context/bootstrap/current-state.md'));
  } finally {
    await fs.rm(projectDir, { recursive: true, force: true });
  }
});
