'use strict';

/**
 * Retired design-doc seed.
 *
 * From 2026-04-12 until 1.63.0 the installer copied a project-level
 * `.aioson/context/design-doc.md` into every project: the framework's OWN
 * code layout (a Node.js CLI — `src/commands/`, `src/lib/{domain}/`,
 * `squad/`, `runner/`, `i18n/messages/`, SQLite tables) under a header that
 * claimed "@dev must load it before any implementation" and "generated by
 * @discovery-design-doc during the pre-dev gate" — a contract no kernel
 * honours. The modular `.aioson/design-docs/` replaced it the day after it
 * was born, but the seed stayed shipped, project-local (never updated),
 * semantically selected on any task naming files or folders, and accepted by
 * the engine as the slug-less fallback for the FEATURE design document.
 *
 * These tests pin the retirement: the template no longer ships it, the
 * selector never offers a verbatim copy, the engine never accepts it as an
 * artifact, and `doctor` names it in the consumer (deleting only a verbatim
 * copy on --fix).
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');

const {
  classifyDesignDocSeed,
  isUsableDesignDocFile,
  inspectDesignDocSeed
} = require('../src/lib/design-doc-seed');
const { selectContext } = require('../src/context-selector');
const { scanArtifacts } = require('../src/preflight-engine');
const { collectContextCatalog, DESIGN_DOC_FILE } = require('../src/context-memory');
const { installTemplate } = require('../src/installer');
const { runDoctor, applyDoctorFixes } = require('../src/doctor');
const { runStateSave } = require('../src/commands/state-save');

const ROOT = path.resolve(__dirname, '..');
const FIXTURES = path.join(__dirname, 'fixtures');

// A project-owned design record that happens to live under the same path —
// a different title, a different heading, none of the retired contract lines.
const PROJECT_RECORD = [
  '---',
  'title: "Design Governance — Desktop workspace"',
  'scope: project',
  'status: approved',
  '---',
  '# Design Doc — Rust workspace',
  '',
  'Crates by responsibility; the UI crate never touches storage directly.',
  'Extract before 500 logic lines; snake_case modules, PascalCase types.',
  ''
].join('\n');

async function seedEn() {
  return fs.readFile(path.join(FIXTURES, 'retired-design-doc-seed.en.md'), 'utf8');
}

async function seedPtBr() {
  return fs.readFile(path.join(FIXTURES, 'retired-design-doc-seed.pt-BR.md'), 'utf8');
}

async function makeTmpDir() {
  return fs.mkdtemp(path.join(os.tmpdir(), 'aioson-design-doc-seed-'));
}

async function writeFile(dir, relPath, content) {
  const full = path.join(dir, relPath);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, content, 'utf8');
  return full;
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeValidContext(dir) {
  await writeFile(
    dir,
    '.aioson/context/project.context.md',
    '---\nproject_name: "demo"\nproject_type: "web_app"\nprofile: "developer"\nframework: "Node"\nframework_installed: true\nclassification: "MICRO"\nconversation_language: "en"\naioson_version: "0.1.9"\n---\n\n# Project Context\n'
  );
}

function quietLogger() {
  const lines = [];
  return { lines, log(value) { lines.push(String(value)); } };
}

// ─── Detector ────────────────────────────────────────────────────────────────

test('every shipped version is verbatim — regardless of line endings, BOM, trailing spaces or final newline', async () => {
  const en = await seedEn();
  const ptBr = await seedPtBr();

  assert.equal(classifyDesignDocSeed(en), 'verbatim');
  assert.equal(classifyDesignDocSeed(ptBr), 'verbatim');
  assert.equal(classifyDesignDocSeed('﻿' + en.replace(/\n/g, '\r\n')), 'verbatim', 'BOM + CRLF (a Windows editor round-trip)');
  assert.equal(classifyDesignDocSeed(en.replace(/\n/g, '  \n')), 'verbatim', 'trailing spaces');
  assert.equal(classifyDesignDocSeed(en.replace(/\n+$/, '')), 'verbatim', 'no final newline');
  assert.equal(classifyDesignDocSeed(ptBr.replace(/\n/g, '\r\n')), 'verbatim', 'pt-BR CRLF');
});

test('an edited copy that keeps the seed header is derived; a project record and an empty file are neither', async () => {
  const en = await seedEn();

  assert.equal(classifyDesignDocSeed(en + '\n## Project addendum\n- our own rule\n'), 'derived', 'body extended');
  assert.equal(
    classifyDesignDocSeed('---\ntitle: "Design Governance — Code Organization Rules"\n---\n# Mine\nrewritten body'),
    'derived',
    'seed title kept'
  );
  assert.equal(classifyDesignDocSeed('# Design Doc — Code Organization\n\nrewritten body'), 'derived', 'seed heading kept');
  assert.equal(
    classifyDesignDocSeed('# Regras\n\n> É gerado/atualizado por `@discovery-design-doc` durante o gate pré-dev.\n'),
    'derived',
    'retired contract line kept (pt-BR)'
  );
  assert.equal(classifyDesignDocSeed(PROJECT_RECORD), null);
  assert.equal(classifyDesignDocSeed(''), null);
  assert.equal(classifyDesignDocSeed('   \n'), null);
});

test('isUsableDesignDocFile: slugged files pass on existence; a slug-less seed is refused; a missing file is not usable', async () => {
  const dir = await makeTmpDir();
  try {
    const slugged = await writeFile(dir, '.aioson/context/design-doc-checkout.md', await seedEn());
    const bare = await writeFile(dir, '.aioson/context/design-doc.md', await seedEn());
    assert.equal(await isUsableDesignDocFile(slugged), true, 'a slugged file is never the seed');
    assert.equal(await isUsableDesignDocFile(bare), false);
    await fs.writeFile(bare, PROJECT_RECORD, 'utf8');
    assert.equal(await isUsableDesignDocFile(bare), true);
    assert.equal(await isUsableDesignDocFile(path.join(dir, '.aioson/context/nope.md')), false);

    const inspected = await inspectDesignDocSeed(dir);
    assert.deepEqual(inspected, { path: '.aioson/context/design-doc.md', exists: true, kind: null });
    await fs.rm(bare);
    assert.deepEqual(await inspectDesignDocSeed(dir), { path: '.aioson/context/design-doc.md', exists: false, kind: null });
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

// ─── Template ────────────────────────────────────────────────────────────────

test('the template no longer ships .aioson/context/design-doc.md', async () => {
  assert.equal(await fileExists(path.join(ROOT, 'template', '.aioson', 'context', 'design-doc.md')), false);
  assert.equal(await fileExists(path.join(ROOT, 'template', '.aioson', 'design-docs', 'folder-structure.md')), true, 'modular governance stays');
});

// ─── Selector ────────────────────────────────────────────────────────────────

test('context:select never offers the verbatim seed, still offers an edited copy for review', async () => {
  const dir = await makeTmpDir();
  try {
    await writeFile(dir, '.aioson/context/project.context.md', '---\nframework: Node.js\n---\n# Project');
    await writeFile(dir, '.aioson/context/project-pulse.md', '---\nactive_feature: (none)\n---\n# Pulse');
    const seedPath = await writeFile(dir, '.aioson/context/design-doc.md', await seedEn());

    const options = {
      agent: 'dev',
      mode: 'executing',
      task: 'create a new module and split a large file, choose folder and file names',
      paths: 'src/commands/new-thing.js',
      semantic: true
    };

    const withSeed = await selectContext(dir, options);
    assert.equal(
      withSeed.selected.some((item) => item.path === '.aioson/context/design-doc.md'),
      false,
      `verbatim seed selected: ${withSeed.selected.map((item) => item.path).join(', ')}`
    );

    await fs.writeFile(seedPath, (await seedEn()) + '\n## Project addendum\n- every folder name is a domain noun\n', 'utf8');
    const withDerived = await selectContext(dir, options);
    assert.equal(
      withDerived.selected.some((item) => item.path === '.aioson/context/design-doc.md'),
      true,
      'an edited copy may hold real project rules and stays selectable'
    );
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

// ─── Engine artifact fallbacks ───────────────────────────────────────────────

test('scanArtifacts: the seed never satisfies the design-doc artifact; a real slug-less record still does; a slugged file wins', async () => {
  const dir = await makeTmpDir();
  try {
    await writeFile(dir, '.aioson/context/project.context.md', '---\nframework: Node.js\n---\n# Project');
    await writeFile(dir, '.aioson/context/design-doc.md', await seedPtBr());
    await writeFile(dir, '.aioson/context/readiness.md', '---\nreadiness: ready\n---\n# Readiness');

    const withSeed = await scanArtifacts(dir, 'checkout');
    assert.equal(withSeed.design_doc.exists, false, 'the seed is not a feature design document');
    assert.equal(withSeed.readiness.exists, true);
    const withSeedNoSlug = await scanArtifacts(dir, null);
    assert.equal(withSeedNoSlug.design_doc.exists, false);

    await writeFile(dir, '.aioson/context/design-doc.md', PROJECT_RECORD);
    const withRecord = await scanArtifacts(dir, 'checkout');
    assert.equal(withRecord.design_doc.exists, true, 'legacy slug-less records keep working');
    assert.ok(withRecord.design_doc.path.endsWith('design-doc.md'));

    await writeFile(dir, '.aioson/context/design-doc.md', await seedEn());
    await writeFile(dir, '.aioson/context/design-doc-checkout.md', '# Checkout design doc\n');
    const withSlugged = await scanArtifacts(dir, 'checkout');
    assert.equal(withSlugged.design_doc.exists, true);
    assert.ok(withSlugged.design_doc.path.endsWith('design-doc-checkout.md'));
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

test('state:save --context=design-doc skips the seed with a warning instead of packaging it', async () => {
  const dir = await makeTmpDir();
  try {
    await writeFile(dir, '.aioson/context/project.context.md', '---\nframework: Node.js\n---\n# Project');
    await writeFile(dir, '.aioson/context/design-doc.md', await seedEn());

    const result = await runStateSave({
      args: [dir],
      options: { feature: 'checkout', next: 'implement the first slice', context: 'design-doc', json: true },
      logger: quietLogger()
    });

    assert.equal(result.ok, true);
    assert.equal((result.context_package || []).includes('design-doc.md'), false, JSON.stringify(result.context_package));
    assert.ok((result.warnings || []).some((line) => /design-doc/.test(line)), JSON.stringify(result.warnings));
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

test('the memory catalog does not advertise the verbatim seed, but lists a project record', async () => {
  const dir = await makeTmpDir();
  try {
    await writeFile(dir, '.aioson/context/design-doc.md', await seedEn());
    const withSeed = await collectContextCatalog(dir);
    assert.equal(withSeed.find((doc) => doc.relPath === DESIGN_DOC_FILE).exists, false);

    await writeFile(dir, '.aioson/context/design-doc.md', PROJECT_RECORD);
    const withRecord = await collectContextCatalog(dir);
    assert.equal(withRecord.find((doc) => doc.relPath === DESIGN_DOC_FILE).exists, true);
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

// ─── Doctor ──────────────────────────────────────────────────────────────────

test('doctor: silent without the file, warns on the seed, --fix deletes a verbatim copy and keeps an edited one', async () => {
  const dir = await makeTmpDir();
  try {
    await installTemplate(dir, { mode: 'install' });
    await writeValidContext(dir);
    const seedPath = path.join(dir, '.aioson', 'context', 'design-doc.md');
    const checkId = 'context:retired_design_doc_seed';

    assert.equal(await fileExists(seedPath), false, 'a fresh install no longer creates the seed');
    const clean = await runDoctor(dir);
    assert.equal(clean.checks.some((check) => check.id === checkId), false);
    assert.equal(clean.livingMemory.retiredDesignDocSeed.exists, false);

    // Verbatim copy (as every older install left it).
    await fs.writeFile(seedPath, (await seedEn()).replace(/\n/g, '\r\n'), 'utf8');
    const verbatim = await runDoctor(dir);
    const verbatimCheck = verbatim.checks.find((check) => check.id === checkId);
    assert.ok(verbatimCheck, 'the seed is named');
    assert.equal(verbatimCheck.ok, false);
    assert.equal(verbatimCheck.severity, 'warning');
    assert.equal(verbatimCheck.params.kind, 'verbatim');
    assert.equal(verbatimCheck.hintKey, 'doctor.retired_design_doc_seed_hint_verbatim');
    assert.equal(verbatimCheck.hintParams.path, '.aioson/context/design-doc.md');
    assert.equal(verbatim.ok, true, 'advisory: never fails the diagnosis');

    const planned = await applyDoctorFixes(dir, verbatim, { dryRun: true });
    const plannedAction = planned.actions.find((action) => action.id === 'retired_design_doc_seed');
    assert.equal(plannedAction.applied, false);
    assert.equal(plannedAction.count, 1);
    assert.equal(await fileExists(seedPath), true, 'dry-run keeps the file');

    const fixed = await applyDoctorFixes(dir, verbatim);
    const fixedAction = fixed.actions.find((action) => action.id === 'retired_design_doc_seed');
    assert.equal(fixedAction.applied, true);
    assert.equal(fixedAction.count, 1);
    assert.equal(await fileExists(seedPath), false, 'a verbatim copy is deleted');
    const afterFix = await runDoctor(dir);
    assert.equal(afterFix.checks.some((check) => check.id === checkId), false);

    // Edited copy: named for review, never deleted.
    await fs.writeFile(seedPath, (await seedEn()) + '\n## Project addendum\n- our own rule\n', 'utf8');
    const derived = await runDoctor(dir);
    const derivedCheck = derived.checks.find((check) => check.id === checkId);
    assert.equal(derivedCheck.params.kind, 'derived');
    assert.equal(derivedCheck.hintKey, 'doctor.retired_design_doc_seed_hint_derived');
    const kept = await applyDoctorFixes(dir, derived);
    const keptAction = kept.actions.find((action) => action.id === 'retired_design_doc_seed');
    assert.equal(keptAction.skipped, true);
    assert.equal(await fileExists(seedPath), true, 'an edited copy is kept');

    // A project-owned record under the same path is not a finding.
    await fs.writeFile(seedPath, PROJECT_RECORD, 'utf8');
    const record = await runDoctor(dir);
    assert.equal(record.checks.some((check) => check.id === checkId), false);
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
});

test('doctor i18n keys for the retired seed exist in en/pt-BR/es/fr', () => {
  const keys = [
    'retired_design_doc_seed',
    'retired_design_doc_seed_hint_verbatim',
    'retired_design_doc_seed_hint_derived',
    'fix_action_retired_design_doc_seed'
  ];
  for (const lang of ['en', 'pt-BR', 'es', 'fr']) {
    const msgs = require(`../src/i18n/messages/${lang}`);
    for (const key of keys) {
      assert.ok(msgs.doctor && msgs.doctor[key], `${lang}: missing doctor.${key}`);
    }
    assert.ok(msgs.doctor.retired_design_doc_seed_hint_verbatim.includes('.aioson/design-docs/'), `${lang}: the hint must point at the modular governance`);
  }
});
