'use strict';

const MANAGED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.gemini/GEMINI.md',
  '.gemini/commands/aios-setup.toml',
  '.gemini/commands/aios-discovery-design-doc.toml',
  '.gemini/commands/aios-analyst.toml',
  '.gemini/commands/aios-architect.toml',
  '.gemini/commands/aios-ux-ui.toml',
  '.gemini/commands/aios-product.toml',
  '.gemini/commands/aios-deyvin.toml',
  '.gemini/commands/aios-pair.toml',
  '.gemini/commands/aios-pm.toml',
  '.gemini/commands/aios-dev.toml',
  '.gemini/commands/aios-qa.toml',
  '.gemini/commands/aios-orchestrator.toml',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/architect.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/product.md',
  '.aioson/agents/deyvin.md',
  '.aioson/agents/pair.md',
  '.aioson/agents/pm.md',
  '.aioson/agents/dev.md',
  '.aioson/agents/qa.md',
  '.aioson/agents/orchestrator.md',
  '.aioson/agents/squad.md',
  '.aioson/agents/genome.md',
  '.aioson/agents/profiler-researcher.md',
  '.aioson/agents/profiler-enricher.md',
  '.aioson/agents/profiler-forge.md',
  '.aioson/locales/en/agents/setup.md',
  '.aioson/locales/en/agents/discovery-design-doc.md',
  '.aioson/locales/en/agents/analyst.md',
  '.aioson/locales/en/agents/architect.md',
  '.aioson/locales/en/agents/ux-ui.md',
  '.aioson/locales/en/agents/product.md',
  '.aioson/locales/en/agents/deyvin.md',
  '.aioson/locales/en/agents/pair.md',
  '.aioson/locales/en/agents/pm.md',
  '.aioson/locales/en/agents/dev.md',
  '.aioson/locales/en/agents/qa.md',
  '.aioson/locales/en/agents/orchestrator.md',
  '.aioson/locales/en/agents/squad.md',
  '.aioson/locales/en/agents/genome.md',
  '.aioson/locales/en/agents/profiler-researcher.md',
  '.aioson/locales/en/agents/profiler-enricher.md',
  '.aioson/locales/en/agents/profiler-forge.md',
  '.aioson/locales/pt-BR/agents/setup.md',
  '.aioson/locales/pt-BR/agents/discovery-design-doc.md',
  '.aioson/locales/pt-BR/agents/analyst.md',
  '.aioson/locales/pt-BR/agents/architect.md',
  '.aioson/locales/pt-BR/agents/ux-ui.md',
  '.aioson/locales/pt-BR/agents/product.md',
  '.aioson/locales/pt-BR/agents/deyvin.md',
  '.aioson/locales/pt-BR/agents/pair.md',
  '.aioson/locales/pt-BR/agents/pm.md',
  '.aioson/locales/pt-BR/agents/dev.md',
  '.aioson/locales/pt-BR/agents/qa.md',
  '.aioson/locales/pt-BR/agents/orchestrator.md',
  '.aioson/locales/pt-BR/agents/squad.md',
  '.aioson/locales/pt-BR/agents/genome.md',
  '.aioson/locales/pt-BR/agents/profiler-researcher.md',
  '.aioson/locales/pt-BR/agents/profiler-enricher.md',
  '.aioson/locales/pt-BR/agents/profiler-forge.md',
  '.aioson/locales/es/agents/setup.md',
  '.aioson/locales/es/agents/discovery-design-doc.md',
  '.aioson/locales/es/agents/analyst.md',
  '.aioson/locales/es/agents/architect.md',
  '.aioson/locales/es/agents/ux-ui.md',
  '.aioson/locales/es/agents/product.md',
  '.aioson/locales/es/agents/deyvin.md',
  '.aioson/locales/es/agents/pair.md',
  '.aioson/locales/es/agents/pm.md',
  '.aioson/locales/es/agents/dev.md',
  '.aioson/locales/es/agents/qa.md',
  '.aioson/locales/es/agents/orchestrator.md',
  '.aioson/locales/es/agents/squad.md',
  '.aioson/locales/es/agents/genome.md',
  '.aioson/locales/es/agents/profiler-researcher.md',
  '.aioson/locales/es/agents/profiler-enricher.md',
  '.aioson/locales/es/agents/profiler-forge.md',
  '.aioson/locales/fr/agents/setup.md',
  '.aioson/locales/fr/agents/discovery-design-doc.md',
  '.aioson/locales/fr/agents/analyst.md',
  '.aioson/locales/fr/agents/architect.md',
  '.aioson/locales/fr/agents/ux-ui.md',
  '.aioson/locales/fr/agents/product.md',
  '.aioson/locales/fr/agents/deyvin.md',
  '.aioson/locales/fr/agents/pair.md',
  '.aioson/locales/fr/agents/pm.md',
  '.aioson/locales/fr/agents/dev.md',
  '.aioson/locales/fr/agents/qa.md',
  '.aioson/locales/fr/agents/orchestrator.md',
  '.aioson/locales/fr/agents/squad.md',
  '.aioson/locales/fr/agents/genome.md',
  '.aioson/locales/fr/agents/profiler-researcher.md',
  '.aioson/locales/fr/agents/profiler-enricher.md',
  '.aioson/locales/fr/agents/profiler-forge.md',
  '.aioson/skills/static/laravel-conventions.md',
  '.aioson/skills/static/tall-stack-patterns.md',
  '.aioson/skills/static/jetstream-setup.md',
  '.aioson/skills/static/rails-conventions.md',
  '.aioson/skills/static/node-express-patterns.md',
  '.aioson/skills/static/node-typescript-patterns.md',
  '.aioson/skills/static/nextjs-patterns.md',
  '.aioson/skills/static/ui-ux-modern.md',
  '.aioson/skills/static/web3-ethereum-patterns.md',
  '.aioson/skills/static/web3-solana-patterns.md',
  '.aioson/skills/static/web3-cardano-patterns.md',
  '.aioson/skills/static/web3-security-checklist.md',
  '.aioson/skills/static/git-conventions.md',
  '.aioson/skills/design/cognitive-core-ui/SKILL.md',
  '.aioson/skills/design/cognitive-core-ui/references/design-tokens.md',
  '.aioson/skills/design/cognitive-core-ui/references/components.md',
  '.aioson/skills/design/cognitive-core-ui/references/patterns.md',
  '.aioson/skills/design/cognitive-core-ui/references/motion.md',
  '.aioson/skills/design/cognitive-core-ui/references/dashboards.md',
  '.aioson/skills/design/cognitive-core-ui/references/websites.md',
  '.aioson/skills/design/premium-command-center-ui/SKILL.md',
  '.aioson/skills/design/premium-command-center-ui/references/visual-system.md',
  '.aioson/skills/design/premium-command-center-ui/references/patterns.md',
  '.aioson/skills/design/premium-command-center-ui/references/operations.md',
  '.aioson/skills/design/premium-command-center-ui/references/validation.md',
  '.aioson/skills/design/interface-design/SKILL.md',
  '.aioson/skills/design/interface-design/references/intent-and-domain.md',
  '.aioson/skills/design/interface-design/references/design-directions.md',
  '.aioson/skills/design/interface-design/references/tokens-and-depth.md',
  '.aioson/skills/design/interface-design/references/components-and-states.md',
  '.aioson/skills/design/interface-design/references/handoff-and-quality.md',
  '.aioson/skills/dynamic/laravel-docs.md',
  '.aioson/skills/dynamic/flux-ui-docs.md',
  '.aioson/skills/dynamic/npm-packages.md',
  '.aioson/skills/dynamic/ethereum-docs.md',
  '.aioson/skills/dynamic/solana-docs.md',
  '.aioson/skills/dynamic/cardano-docs.md',
  '.aioson/mcp/servers.md',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/schemas/squad-manifest.schema.json',
  '.aioson/schemas/squad-blueprint.schema.json',
  '.aioson/schemas/readiness.schema.json',
  '.aioson/schemas/content-blueprint.schema.json',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/tasks/squad-design.md',
  '.aioson/tasks/squad-create.md',
  '.aioson/tasks/squad-validate.md',
  '.aioson/tasks/squad-analyze.md',
  '.aioson/tasks/squad-extend.md',
  '.aioson/tasks/squad-export.md',
  '.aioson/tasks/squad-repair.md',
  '.aioson/tasks/squad-pipeline.md',
  '.aioson/profiler-reports/.gitkeep',
  '.aioson/advisors/.gitkeep'
];

const REQUIRED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.gemini/GEMINI.md',
  '.gemini/commands/aios-setup.toml',
  '.gemini/commands/aios-discovery-design-doc.toml',
  '.gemini/commands/aios-analyst.toml',
  '.gemini/commands/aios-architect.toml',
  '.gemini/commands/aios-ux-ui.toml',
  '.gemini/commands/aios-pm.toml',
  '.gemini/commands/aios-dev.toml',
  '.gemini/commands/aios-qa.toml',
  '.gemini/commands/aios-orchestrator.toml',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/dev.md',
  '.aioson/context/.gitkeep'
];

const CONTEXT_REQUIRED_FIELDS = [
  'project_name',
  'project_type',
  'profile',
  'framework',
  'framework_installed',
  'classification',
  'conversation_language',
  'aioson_version'
];

const CONTEXT_ALLOWED_CLASSIFICATIONS = ['MICRO', 'SMALL', 'MEDIUM'];
const CONTEXT_ALLOWED_PROJECT_TYPES = ['web_app', 'api', 'site', 'script', 'dapp'];
const CONTEXT_ALLOWED_PROFILES = ['developer', 'beginner', 'team'];

const AGENT_DEFINITIONS = [
  {
    id: 'setup',
    displayName: 'Setup',
    command: '@setup',
    path: '.aioson/agents/setup.md',
    dependsOn: [],
    output: '.aioson/context/project.context.md'
  },
  {
    id: 'discovery-design-doc',
    displayName: 'Discovery/Design Doc',
    command: '@discovery-design-doc',
    path: '.aioson/agents/discovery-design-doc.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/design-doc.md + .aioson/context/readiness.md'
  },
  {
    id: 'product',
    displayName: 'Product',
    command: '@product',
    path: '.aioson/agents/product.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/prd.md or .aioson/context/prd-{slug}.md (PRD base)'
  },
  {
    id: 'deyvin',
    displayName: 'Deyvin',
    command: '@deyvin',
    path: '.aioson/agents/deyvin.md',
    aliases: ['pair'],
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'small code changes + continuity notes in spec.md + runtime logs/tasks'
  },
  {
    id: 'analyst',
    displayName: 'Analyst',
    command: '@analyst',
    path: '.aioson/agents/analyst.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/discovery.md'
  },
  {
    id: 'architect',
    displayName: 'Architect',
    command: '@architect',
    path: '.aioson/agents/architect.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/discovery.md'
    ],
    output: '.aioson/context/architecture.md'
  },
  {
    id: 'ux-ui',
    displayName: 'UI/UX',
    command: '@ux-ui',
    path: '.aioson/agents/ux-ui.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md'
    ],
    output: '.aioson/context/ui-spec.md + Visual identity enrichment in prd.md or prd-{slug}.md'
  },
  {
    id: 'pm',
    displayName: 'PM',
    command: '@pm',
    path: '.aioson/agents/pm.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md'
    ],
    output: '.aioson/context/prd.md or prd-{slug}.md (enriched with delivery plan and acceptance criteria)'
  },
  {
    id: 'dev',
    displayName: 'Dev',
    command: '@dev',
    path: '.aioson/agents/dev.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md'
    ],
    output: 'code changes'
  },
  {
    id: 'qa',
    displayName: 'QA',
    command: '@qa',
    path: '.aioson/agents/qa.md',
    dependsOn: ['.aioson/context/discovery.md'],
    output: 'QA report'
  },
  {
    id: 'orchestrator',
    displayName: 'Orchestrator',
    command: '@orchestrator',
    path: '.aioson/agents/orchestrator.md',
    dependsOn: [
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md',
      '.aioson/context/prd.md'
    ],
    output: '.aioson/context/parallel/*.status.md'
  },
  {
    id: 'squad',
    displayName: 'Squad',
    command: '@squad',
    path: '.aioson/agents/squad.md',
    dependsOn: [],
    output:
      '.aioson/squads/{slug}/squad.manifest.json + .aioson/squads/{slug}/squad.md + .aioson/squads/{slug}/agents/ + .aioson/squads/{slug}/workers/ + .aioson/squads/{slug}/workflows/ + .aioson/squads/{slug}/checklists/ + .aioson/squads/{slug}/skills/ + .aioson/squads/{slug}/templates/ + .aioson/squads/{slug}/docs/ + output/{slug}/{session-id}.html + output/{slug}/{content-key}/content.json + output/{slug}/{content-key}/index.html + output/{slug}/latest.html + aioson-logs/{slug}/ + media/{slug}/'
  },
  {
    id: 'genome',
    displayName: 'Genome',
    command: '@genome',
    path: '.aioson/agents/genome.md',
    dependsOn: [],
    output: '.aioson/genomes/[slug].md + .aioson/genomes/[slug].meta.json + optional binding in .aioson/squads/{slug}/squad.md or .aioson/squads/{slug}/squad.manifest.json'
  },
  {
    id: 'profiler-researcher',
    displayName: 'Profiler Researcher',
    command: '@profiler-researcher',
    path: '.aioson/agents/profiler-researcher.md',
    dependsOn: [],
    output: '.aioson/profiler-reports/{person-slug}/research-report.md'
  },
  {
    id: 'profiler-enricher',
    displayName: 'Profiler Enricher',
    command: '@profiler-enricher',
    path: '.aioson/agents/profiler-enricher.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/research-report.md'],
    output: '.aioson/profiler-reports/{person-slug}/enriched-profile.md'
  },
  {
    id: 'profiler-forge',
    displayName: 'Profiler Forge',
    command: '@profiler-forge',
    path: '.aioson/agents/profiler-forge.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/enriched-profile.md'],
    output: '.aioson/genomes/{person-slug}-{domain-slug}.md + .aioson/genomes/{person-slug}-{domain-slug}.meta.json + .aioson/advisors/{person-slug}-advisor.md'
  }
];

module.exports = {
  MANAGED_FILES,
  REQUIRED_FILES,
  CONTEXT_REQUIRED_FIELDS,
  CONTEXT_ALLOWED_CLASSIFICATIONS,
  CONTEXT_ALLOWED_PROJECT_TYPES,
  CONTEXT_ALLOWED_PROFILES,
  AGENT_DEFINITIONS
};
